[package]
name = "lastfm-reports"
version = "0.1.0"
authors = ["wilspi <thewilspi@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version="0.10.8", features=["blocking", "json"]}
serde = {version="1.0.111", features=["derive"]}
serde_json = "1.0.55"
